apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-monitoring
  namespace: lab-monitoring
spec:
  version: __ES_VERSION__
  http:
    tls:
      certificate:
        secretName: es-monitoring-tls
  nodeSets:
    - name: default
      count: __MONITORING_ES_NODES__
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: "__MONITORING_ES_CPU__"
                  memory: __MONITORING_ES_MEMORY__
                limits:
                  memory: __MONITORING_ES_MEMORY__
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-monitoring
  namespace: lab-monitoring
spec:
  version: __ES_VERSION__
  count: 1
  elasticsearchRef:
    name: elasticsearch-monitoring
  http:
    tls:
      certificate:
        secretName: es-monitoring-tls
